# version x.x.x corresponds to "latest"
dependencies:

  - name: reloader
    version: v1.0.15
    repository: https://stakater.github.io/stakater-charts
    condition: reloader.enabled

  - name: postgresql
    version: 12.2.7
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.14.1
  
  - name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: 14.4.6
    condition: mongodb.enabled
