apiVersion: v1
kind: Service
metadata:
  annotations:

  labels:
    io.kompose.service: {{ .Release.Name }}-studio-db
  name: {{ .Release.Name }}-studio-db
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: {{ .Release.Name }}-studio-db
