{{- if (include "stackn.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  studio-superuser-password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "studio-superuser-password" "providedValues" (list "global.studio.superuserPassword" "studio.superuserPassword") "context" $) }}
  studio-event-listener-user-password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "studio-event-listener-user-password" "providedValues" (list "global.studio.eventListenerUserPassword" "studio.eventListenerUserPassword") "context" $) }}
  studio-log-collector-user-password: {{ .Values.studio.logCollectorUserPassword | b64enc }}
  studio-argocd-token: {{ .Values.studio.argocd.token | b64enc }}
  django-secret-key:  {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "django-secret-key" "providedValues" (list "studio.djangoSecret") "length" 50 "strong" true "context" $) }}
  {{ if .Values.studio.emailService.enabled }}
  email-host-user: {{ .Values.studio.emailService.hostUser | b64enc }}
  email-host-password: {{ .Values.studio.emailService.hostPassword | b64enc }}
  email-api-key: {{ .Values.studio.emailService.apiKey | b64enc }}
  {{ end }}
  {{ if .Values.studio.harbor.enabled }}
  harbor-creds: {{ printf "%s:%s" .Values.studio.harbor.username .Values.studio.harbor.password | b64enc | b64enc }}
  {{ end }}
{{- end -}}