{{- if (include "stackn.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  studio-superuser-password: {{ include "stackn.studio.superuser.password" . | b64enc | quote }}
  rabbit-password: {{ include "stackn.rabbit.password" . | b64enc | quote }}
  postgresql-password: {{ include "stackn.studio.postgres.password" . | b64enc | quote }}
  postgresql-postgres-password: {{ include "stackn.studio.postgresql-postgres.password" . | b64enc | quote }}
{{- end -}}