apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-celery-flower
spec:
  ports:
  - name: "5556"
    port: 5556
    targetPort: 5556
  selector:
    name: {{ .Release.Name }}-celery-flower
status:
  loadBalancer: {}
