{{- if .Values.celeryFlower.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    io.kompose.service: {{ .Release.Name }}-celery-flower
    name: {{ .Release.Name }}-celery-flower
  name: {{ .Release.Name }}-celery-flower
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: {{ .Release.Name }}-celery-flower
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Release.Name }}-celery-flower
        name: {{ .Release.Name }}-celery-flower
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
          - sh
          - ./scripts/run_flower.sh
        {{- if .Values.studio.securityContext.enabled }}
        securityContext:
          runAsUser: {{ .Values.studio.securityContext.runAsUser }}
          runAsGroup: {{ .Values.studio.securityContext.runAsGroup }}
        {{- end }}
        env:
        - name: BASE_PATH
          value: "/app"
        - name: GET_HOSTS_FROM
          value: dns
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "stackn.postgres.secretName" . }}
              key: password
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.global.postgresql.auth.user }}
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: {{ template "stackn.secretName" . }}
              key: rabbit-password
        - name: RABBITMQ_HOST
          value: {{ .Release.Name }}-rabbit
        - name: RABBITMQ_USER
          value: {{ include "stackn.rabbit.username" . }}
        - name: REDIS_HOST
          value: {{ .Release.Name }}-redis
        {{- if .Values.chartcontroller.addSecret }}
        - name: KUBECONFIG
          value: {{ .Values.studio.kubeconfig_file | quote }}
        {{- end }}
        image: {{ .Values.studio.image.repository }}
        imagePullPolicy: {{ .Values.studio.image.pullPolicy }}
        name: {{ .Release.Name }}-celery-worker
        resources:
          limits:
            cpu: {{ .Values.celeryWorkers.resources.limits.cpu }}
            memory: {{ .Values.celeryWorkers.resources.limits.memory }}
          requests:
            cpu: {{ .Values.celeryWorkers.resources.requests.cpu }}
            memory: {{ .Values.celeryWorkers.resources.requests.memory }}
        volumeMounts:
          {{- if .Values.chartcontroller.addSecret }}
          - name: config
            mountPath: {{ .Values.studio.kubeconfig_dir | quote }}
            readOnly: true
          {{- end }}
          - mountPath: /app/studio/settings.py
            subPath: settings.py
            name: {{ .Release.Name}}-settings-configmap
      imagePullSecrets:
        - name: ghcrsecret
      restartPolicy: Always
      volumes:
      {{- if .Values.chartcontroller.addSecret }}
      - name: config
        secret:
          secretName: {{ .Release.Name }}-chart-controller-secret
      {{- end }}
      - name: {{ .Release.Name}}-settings-configmap
        configMap:
          name: {{ .Release.Name}}-settings-configmap
          items:
          - key: settings.py
            path: settings.py

status: {}
{{- end }}
