{{- if .Values.chartcontroller.addSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-chart-controller-secret
type: Opaque
data:
  config: <your-k8s-config> #See values-utility-script.sh 
{{- end }}
