{{- if .Values.chartcontroller.addSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-chart-controller-secret
type: Opaque
stringData:
  config: {{ toYaml .Values.cluster_config | indent 2 }}

{{- end }}
