{{- if .Values.chartcontroller.addSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-chart-controller-secret
type: Opaque
data:
  config: {{ .Values.kubeconfig }} 
{{- end }}
