apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fednnext-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: fedn.test.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fedn-frontend-service
                port:
                  number: 80
  # TLS can be configured here if needed
  # tls:
  # - hosts:
  #     - fednnext.test.local
  #   secretName: my-tls-secret
