apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-studio-media
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
  - {{ .Values.studio.media.storage.accessModes  | default "ReadWriteMany"}}
  storageClassName: {{ include "stackn.studio.media.storageclass" . }}
  resources:
    requests:
      storage: {{ .Values.studio.media.storage.size | default "5Gi" }}
