apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo-express
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.mongoexpress.service.port }}
    targetPort: 8081
    protocol: TCP
  selector:
    release: {{ .Release.Name }}