apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-static
  namespace: {{ .Values.namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.studio.static.replicas }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: stackn-studio
      type: app
      pod: nginx-static
  strategy:
      type: {{ .Values.studio.static.strategy.type }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8501"
      labels:
        release: {{ .Release.Name }}
        app: stackn-studio
        type: app
        pod: nginx-static
    spec:
      automountServiceAccountToken: false
      volumes:
      - name: rp-conf
        configMap:
          name: {{ .Release.Name }}-static-config
      containers:
      - name: static
        image: "{{ .Values.studio.static.image | default "harbor.scaleoutsystems.com/studio/studio-nginx:{{ .Chart.appVersion }}" }}"
        imagePullPolicy: {{ .Values.studio.static.pullPolicy }}
        # securityContext:
        #   runAsUser: 101
        #   runAsGroup: 101
        #   allowPrivilegeEscalation: false
        #   privileged: false
        #   capabilities:
        #     drop:
        #       - all
        volumeMounts:
        - name: rp-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          limits:
            cpu: {{ .Values.studio.static.resources.limits.cpu }}
            memory: {{ .Values.studio.static.resources.limits.memory }}
          requests:
            cpu: {{ .Values.studio.static.resources.requests.cpu }}
            memory: {{ .Values.studio.static.resources.requests.memory }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
