{{ if not .Values.studio.debug }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-static
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    release: {{ .Release.Name }}
    pod: nginx-static
status:
  loadBalancer: {}
{{ end }}