apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-rabbit
    name: {{ .Release.Name }}-rabbit
  name: {{ .Release.Name }}-rabbit
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-rabbit
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Release.Name }}-rabbit
        name: {{ .Release.Name }}-rabbit
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: {{ include "stackn.secretName" . }}
              key: rabbit-password
        - name: RABBITMQ_DEFAULT_USER
          value: {{ include "stackn.rabbit.username" . }}
        image: rabbitmq:3.8
        name: {{ .Release.Name }}-rabbit
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources: {}
      hostname: rabbit
      restartPolicy: Always
status: {}
