apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-redis
    name: {{ .Release.Name }}-redis
  name: {{ .Release.Name }}-redis
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-redis
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Release.Name }}-redis
        name: {{ .Release.Name }}-redis
    spec:
      containers:
      - image: redis
        name: {{ .Release.Name }}-redis
        ports:
        - containerPort: 6379
        resources: {}
      hostname: redis
      restartPolicy: Always
status: {}
