apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
  selector:
    app: fedn-frontend