apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.studio.servicename }}
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    name: {{ .Release.Name }}-{{ .Values.studio.servicename }}
status:
  loadBalancer: {}
