apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stackn-admin
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }}

