apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-studio
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    name: {{ .Release.Name }}-studio
status:
  loadBalancer: {}
