apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: celery-worker-claim0
  name: celery-worker-claim0
spec:
  storageClassName: {{ .Values.repositories.storageClassName }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
