name: Release Helm charts

on:
  push:
    branches:
      - master
      - fix/*

jobs:
  chart-releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "desislava@scaleoutsystems.com"
          
      - name: Install Helm
        run: |
          curl -sSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm init --client-only

      - name: Add chart dependencies
        run: |
          helm repo add stable https://charts.helm.sh/stable
          
      - name: Update gh-pages repo
        run: |
          git clone https://github.com/scaleoutsystems/charts.git -b gh-pages
          cd charts
          helm repo index scaleout/stackn/
          git add .
          git commit -m "Updated scaleout/stackn/index.yml"
          git push
