name: Release Helm charts

on:
  push:
    branches:
      - master

jobs:
  chart-releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
      - name: Install Helm
        run: |
          curl -sSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm init --client-only

      - name: Add chart dependencies
        run: |
          helm repo add stable https://charts.helm.sh/stable

      - name: Generate index.yaml files
        run: |
          echo "helm repo index ..."
          helm repo index scaleout/cronjob/
          helm repo index scaleout/deploy/
          helm repo index scaleout/lab/
          helm repo index scaleout/project/
          helm repo index scaleout/stackn/
          helm repo index scaleout/volume/
