name: Release Helm charts

on:
  push:
    branches:
      - master

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Merge master -> gh-pages
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: gh-pages
          github_token: ${{ secrets.CR_TOKEN }}
  
  chart-releaser:
    runs-on: ubuntu-latest
    needs: sync-branch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Configure Git
        run: |
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm init --client-only

      - name: Add chart dependencies
        run: |
          helm repo add stable https://charts.helm.sh/stable
      
      - name: Remove existing index.yaml
        run: |
          FILE=scaleout/stackn/index.yaml
          if [ -f "$FILE" ]; then
              rm scaleout/stackn/index.yaml
          fi
      
      - name: Remove existing helm package
        run: |
          rm -v scaleout/stackn/stackn-* || true
          
      - name: Update index.yaml and helm package
        run: |
          cd scaleout/stackn
          helm package .
          helm repo index . --url https://scaleoutsystems.github.io/charts/scaleout/stackn

      - name: Commit index.yaml and helm package to gh-pages
        run: |
          git pull origin gh-pages
          git add -A
          git commit -m "Updated index.yaml and helm package"
          git push origin gh-pages
          
